blank_issues_enabled: false

# Issueä½œæˆæ™‚ã®ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆè¨­å®š
defaults:
  - template: "fix.yml"
    name: "ğŸ› ãƒã‚°ä¿®æ­£"
    about: "ãƒã‚°ã‚’å ±å‘Š and ä¿®æ­£ã™ã‚‹"
  - template: "feature-frontend.yml"
    name: "ğŸ’¡ æ©Ÿèƒ½è¿½åŠ : frontend"
    about: "frontendã«æ©Ÿèƒ½è¿½åŠ ã‚’ã™ã‚‹"
  - template: "feature-backend.yml"
    name: "ğŸ’¡ æ©Ÿèƒ½è¿½åŠ : backend"
    about: "backendã«æ©Ÿèƒ½è¿½åŠ ã‚’ã™ã‚‹"
